version: '3'

services:
  gast:
    build: bordados
    mem_limit: 512m
    ports:
      - "8080:8080"
    env_file: .env  # ¡Clave! Carga las variables desde el .env
    environment:
      - DB_URL=${DB_URL}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SP_PUBLIC=${SP_PUBLIC}
      - SP_SECRET=${SP_SECRET}
      - APP_UPLOAD_DIR=${APP_UPLOAD_DIR}
    volumes:
      - ./images:/app/images
    restart: always
    depends_on:
      gast_shop:
        condition: service_healthy

  gast_shop:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  # Usa la misma contraseña del .env
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=ecommerce_bordados
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - gast_db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

volumes:
  gast_db_data:
  gast_images: